ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_SKETCHBOOK = /home/arduino/sketchbook

USER_LIB_PATH = /home/arduino/libraries
BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk
